# Generated by Django 4.1.5 on 2023-12-22 07:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('biography', wagtail.fields.RichTextField(verbose_name='Биография')),
                ('preview_biography', wagtail.fields.RichTextField(verbose_name='Превью биографии')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('death_date', models.DateField(verbose_name='Дата смерти')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Усопший',
                'verbose_name_plural': 'Усопшие',
                'ordering': ['-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DeceasedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Документ файла')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='svo.deceasedpage')),
            ],
            options={
                'verbose_name': 'Файл усопшего',
                'verbose_name_plural': 'Файлы усопших',
            },
        ),
        migrations.CreateModel(
            name='DeceasedAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название награды')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение награды')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='svo.deceasedpage')),
            ],
            options={
                'verbose_name': 'Награда усопшего',
                'verbose_name_plural': 'Награды усопших',
            },
        ),
    ]
