# Generated by Django 4.1.3 on 2022-11-23 06:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Страница с вкладками и материалами',
                'verbose_name_plural': 'Страницы с вкладками и материалами',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.StreamField([('navigation', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст ссылки')), ('url', wagtail.blocks.CharBlock(label='Адрес ссылки')), ('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате'))]), label='Cсылки')), ('hidden_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст ссылки')), ('url', wagtail.blocks.CharBlock(label='Адрес ссылки'))]), label='Спрятанные ссылки'))], label='Блок навигации')), ('meta', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(label='Заголовок')), ('content', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(label='Текстовое поле')), ('contacts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('text', wagtail.blocks.TextBlock(label='Текст'))], label='Элемент списка'), label='Список контактов'))], label='Контент', max_num=1))]), label='Колонки'))], label='Блок информации'))], use_json_field=True, verbose_name='Контент подвала')),
            ],
            options={
                'verbose_name': 'Подвал',
                'verbose_name_plural': 'Подвалы',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.StreamField([('navigation', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('logo', wagtail.blocks.RawHTMLBlock(label='Лого в svg формате')), ('links', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст ссылки')), ('url', wagtail.blocks.CharBlock(label='Адрес ссылки')), ('children', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст ссылки')), ('url', wagtail.blocks.CharBlock(label='Адрес ссылки'))]), label='Дочерние ссылки'))], label='Ссылки'))], label='Блок навигации')), ('meta', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('columns', wagtail.blocks.StreamBlock([('contact', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('text', wagtail.blocks.TextBlock(label='Текст'))], label='Блок с иконкой и текстом')), ('search', wagtail.blocks.StructBlock([('action_url', wagtail.blocks.CharBlock(help_text='Ссылка на страницу, на которой применится поиск', label='Место действия')), ('hint', wagtail.blocks.CharBlock(label='Подсказка'))], label='Поиск')), ('social_link', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('code', wagtail.blocks.CharBlock(label='Код социальной сети')), ('url', wagtail.blocks.CharBlock(label='Адрес ссылки'))], label='Иконка с ссылкой'))]))], label='Блок информации'))], use_json_field=True, verbose_name='Контент шапки')),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапки',
            },
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('spacer', wagtail.blocks.StructBlock([('height', wagtail.blocks.CharBlock(label='Размер вертикального разрыва'))], help_text='Отступ между элементами', label='Разрыв контента')), ('section_title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], help_text='Название секции', label='Название секции')), ('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'p', 'bold', 'italic'], help_text='Вводите текст и изменяйте его', label='Редактор текста')), ('youtube', wagtail.embeds.blocks.EmbedBlock(help_text='Вводите ссылку на видео', icon='success', label='Видео')), ('banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))], help_text='Блок с картинкой', label='Баннер')), ('banners_slider', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображение'), label='Список изображений'))], help_text='Список блочных картинок(слайдер)', label='Карусель баннеров')), ('government_services_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('title', wagtail.blocks.CharBlock(label='Заголовок')), ('sub_title', wagtail.blocks.CharBlock(label='Подзаголовок')), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], label='Кнопка')), ('background_image', wagtail.images.blocks.ImageChooserBlock(label='Задний план баннера'))], help_text='Баннер госуслуг', label='Государственный баннер')), ('map', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('logo', wagtail.blocks.RawHTMLBlock(label='Лого в формате svg')), ('url', wagtail.blocks.CharBlock(label='Ссылка на карту')), ('text', wagtail.blocks.RichTextBlock(label='Текст для карты')), ('social', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Информация социальной сети'))], help_text='Гугл карта с данными', label='Карта')), ('partners', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('partners', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Лого')), ('name', wagtail.blocks.RichTextBlock(label='Название')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Партнёр'), label='Список партнёров'))], help_text='Список партнёров', label='Партнёры')), ('statistics_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('statistics', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.CharBlock(label='Значение')), ('description', wagtail.blocks.CharBlock(label='Описание'))], label='Элемент Статистики'))), ('image', wagtail.images.blocks.ImageChooserBlock(label='Заднее изображение баннера'))], help_text='Баннер со статистикой', label='Статистический Баннер'))], use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Простая страница с контентом',
                'verbose_name_plural': 'Простые страницы с контентом',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ComplexPageTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='название вкладки')),
                ('body', wagtail.fields.StreamField([('spacer', wagtail.blocks.StructBlock([('height', wagtail.blocks.CharBlock(label='Размер вертикального разрыва'))], help_text='Отступ между элементами', label='Разрыв контента')), ('section_title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], help_text='Название секции', label='Название секции')), ('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'p', 'bold', 'italic'], help_text='Вводите текст и изменяйте его', label='Редактор текста')), ('youtube', wagtail.embeds.blocks.EmbedBlock(help_text='Вводите ссылку на видео', icon='success', label='Видео')), ('banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))], help_text='Блок с картинкой', label='Баннер')), ('banners_slider', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображение'), label='Список изображений'))], help_text='Список блочных картинок(слайдер)', label='Карусель баннеров')), ('government_services_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('title', wagtail.blocks.CharBlock(label='Заголовок')), ('sub_title', wagtail.blocks.CharBlock(label='Подзаголовок')), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], label='Кнопка')), ('background_image', wagtail.images.blocks.ImageChooserBlock(label='Задний план баннера'))], help_text='Баннер госуслуг', label='Государственный баннер')), ('map', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('logo', wagtail.blocks.RawHTMLBlock(label='Лого в формате svg')), ('url', wagtail.blocks.CharBlock(label='Ссылка на карту')), ('text', wagtail.blocks.RichTextBlock(label='Текст для карты')), ('social', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Информация социальной сети'))], help_text='Гугл карта с данными', label='Карта')), ('partners', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('partners', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Лого')), ('name', wagtail.blocks.RichTextBlock(label='Название')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Партнёр'), label='Список партнёров'))], help_text='Список партнёров', label='Партнёры')), ('statistics_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('statistics', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.CharBlock(label='Значение')), ('description', wagtail.blocks.CharBlock(label='Описание'))], label='Элемент Статистики'))), ('image', wagtail.images.blocks.ImageChooserBlock(label='Заднее изображение баннера'))], help_text='Баннер со статистикой', label='Статистический Баннер'))], use_json_field=True, verbose_name='Контент вкладки')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='pages.complexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexPageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Картинка')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pages.complexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
