# Generated by Django 4.1.3 on 2022-11-23 06:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('spacer', wagtail.blocks.StructBlock([('height', wagtail.blocks.CharBlock(label='Размер вертикального разрыва'))], help_text='Отступ между элементами', label='Разрыв контента')), ('section_title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], help_text='Название секции', label='Название секции')), ('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'p', 'bold', 'italic'], help_text='Вводите текст и изменяйте его', label='Редактор текста')), ('youtube', wagtail.embeds.blocks.EmbedBlock(help_text='Вводите ссылку на видео', icon='success', label='Видео')), ('banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))], help_text='Блок с картинкой', label='Баннер')), ('banners_slider', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображение'), label='Список изображений'))], help_text='Список блочных картинок(слайдер)', label='Карусель баннеров')), ('government_services_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('title', wagtail.blocks.CharBlock(label='Заголовок')), ('sub_title', wagtail.blocks.CharBlock(label='Подзаголовок')), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], label='Кнопка')), ('background_image', wagtail.images.blocks.ImageChooserBlock(label='Задний план баннера'))], help_text='Баннер госуслуг', label='Государственный баннер')), ('map', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('logo', wagtail.blocks.RawHTMLBlock(label='Лого в формате svg')), ('url', wagtail.blocks.CharBlock(label='Ссылка на карту')), ('text', wagtail.blocks.RichTextBlock(label='Текст для карты')), ('social', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(label='Иконка в svg формате')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Информация социальной сети'))], help_text='Гугл карта с данными', label='Карта')), ('partners', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('partners', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Лого')), ('name', wagtail.blocks.RichTextBlock(label='Название')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Партнёр'), label='Список партнёров'))], help_text='Список партнёров', label='Партнёры')), ('statistics_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('statistics', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.CharBlock(label='Значение')), ('description', wagtail.blocks.CharBlock(label='Описание'))], label='Элемент Статистики'))), ('image', wagtail.images.blocks.ImageChooserBlock(label='Заднее изображение баннера'))], help_text='Баннер со статистикой', label='Статистический Баннер'))], use_json_field=True, verbose_name='Контент')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
