# Generated by Django 4.1.3 on 2022-11-23 19:54

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'ordering': ['-id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('spacer', wagtail.blocks.StructBlock([('height', wagtail.blocks.CharBlock(label='Размер вертикального разрыва'))], help_text='Отступ между элементами', label='Разрыв контента')), ('section_title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], help_text='Название секции', label='Название секции')), ('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'p', 'bold', 'italic'], help_text='Вводите текст и изменяйте его', label='Редактор текста')), ('youtube', wagtail.embeds.blocks.EmbedBlock(help_text='Вводите ссылку на видео', icon='success', label='Видео')), ('banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))], help_text='Блок с картинкой', label='Баннер')), ('banners_slider', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображение'), label='Список изображений'))], help_text='Список блочных картинок(слайдер)', label='Карусель баннеров')), ('government_services_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('title', wagtail.blocks.CharBlock(label='Заголовок')), ('sub_title', wagtail.blocks.CharBlock(label='Подзаголовок')), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст'))], label='Кнопка')), ('background_image', wagtail.images.blocks.ImageChooserBlock(label='Задний план баннера'))], help_text='Баннер госуслуг', label='Государственный баннер')), ('map', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('logo', wagtail.blocks.RawHTMLBlock(help_text='html-разметка', label='Лого в формате svg')), ('url', wagtail.blocks.CharBlock(label='Ссылка на карту')), ('text', wagtail.blocks.RichTextBlock(label='Текст для карты')), ('social', wagtail.blocks.StructBlock([('icon', wagtail.blocks.RawHTMLBlock(help_text='html-разметка', label='Иконка в svg формате')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Информация социальной сети'))], help_text='Гугл карта с данными', label='Карта')), ('partners', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('partners', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Лого')), ('name', wagtail.blocks.RichTextBlock(label='Название')), ('url', wagtail.blocks.CharBlock(label='Ссылка'))], label='Партнёр'), label='Список партнёров'))], help_text='Список партнёров', label='Партнёры')), ('statistics_banner', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(label='Идентификатор')), ('statistics', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.CharBlock(label='Значение')), ('description', wagtail.blocks.CharBlock(label='Описание'))], label='Элемент Статистики'))), ('image', wagtail.images.blocks.ImageChooserBlock(label='Заднее изображение баннера'))], help_text='Баннер со статистикой', label='Статистический Баннер'))], use_json_field=True, verbose_name='Контент'),
        ),
    ]
